import React from "react";
import { createRoot } from "react-dom/client";
import "./styles.css";

type Stats={users:number;posts:number;pending:number;moderation:number};
type ReportItem={id:string;reason:string;details:string|null;createdAt:string;post:{id:string;title:string};reporter:{firstName:string|null;username:string|null;telegramId:string}};
type QueueItem={id:string;title:string|null;body:string|null;category:string|null;moderationJson:string|null;createdAt:string;user:{firstName:string|null;username:string|null;telegramId:string}};
type Analytics={period:{days:number;since:string};overview:Record<string,number>;series:Array<{date:string;users:number;posts:number;views:number;reactions:number;comments:number;reports:number;moderation:number;xp:number}>;content:{categories:Array<{category:string;count:number}>;topCreators:Array<{id:string;firstName:string|null;username:string|null;_count:{posts:number;followers:number}}>} ;safety:{moderationByAction:Array<{action:string;count:number}>;reportsByReason:Array<{reason:string;count:number}>}};
type SafetyEvent={id:string;action:string;reason:string|null;createdAt:string;targetUser:{id:string;telegramId:string;username:string|null;firstName:string|null;blocked:boolean;restrictedUntil:string|null}|null;moderator:{id:string;username:string|null;firstName:string|null}|null};
type OppItem={id:string;title:string;description:string;organization:string;type:string;category:string;location:string|null;deadline:string|null;applicationUrl:string|null;verified:boolean;active:boolean;createdAt:string;owner:{id:string;firstName:string|null;username:string|null}|null;_count:{saves:number}};
type UserItem={id:string;telegramId:string;username:string|null;firstName:string|null;role:string;blocked:boolean;restrictedUntil:string|null;createdAt:string;xp:number;level:number;_count:{posts:number;followers:number;following:number;comments:number}};
const API=import.meta.env.VITE_API_URL??"http://localhost:3000";
const labels:Record<string,string>={users:"👥 ተጠቃሚዎች",posts:"📝 ፖስቶች",communities:"🏘️ ማህበረሰቦች",communityMembers:"👨‍👩‍👧 አባላት",opportunities:"🚀 እድሎች",events:"🎉 ዝግጅቶች",polls:"🗳️ ምርጫዎች",quizzes:"🧠 ክዊዞች",views:"👁️ እይታዎች",reactions:"❤️ ምላሾች",comments:"💬 አስተያየቶች",openReports:"🚩 ክፍት ሪፖርቶች",moderationEvents:"🛡️ የሞዴሬሽን ክስተቶች",xpEvents:"⭐ XP ክስተቶች",eventRsvps:"🙋 RSVP",pollVotes:"🗳️ ድምጾች",quizAnswers:"🧠 መልሶች"};
function App(){
 const [key,setKey]=React.useState(localStorage.getItem("genzi_admin_key")??"");
 const [moderatorToken,setModeratorToken]=React.useState(localStorage.getItem("genzi_moderator_session")??"");
 const [moderatorLabel,setModeratorLabel]=React.useState(localStorage.getItem("genzi_moderator_label")??"");
 const [code,setCode]=React.useState("");
 const [stats,setStats]=React.useState<Stats|null>(null);const [analytics,setAnalytics]=React.useState<Analytics|null>(null);const [users,setUsers]=React.useState<UserItem[]>([]);const [queue,setQueue]=React.useState<QueueItem[]>([]);const [reports,setReports]=React.useState<ReportItem[]>([]);const [tab,setTab]=React.useState<"overview"|"analytics"|"safety"|"users"|"opportunities">("overview");const [error,setError]=React.useState("");
 const [safetyEvents,setSafetyEvents]=React.useState<SafetyEvent[]>([]);const [opps,setOpps]=React.useState<OppItem[]>([]);const [oppDraft,setOppDraft]=React.useState({title:"",description:"",organization:"",type:"JOB",category:"ስራ",applicationUrl:""});
 const headers=React.useMemo(()=>({"X-Admin-Key":key,...(moderatorToken?{"X-Moderator-Session":moderatorToken}:{})}),[key,moderatorToken]);
 const load=React.useCallback(async()=>{if(!key)return;setError("");try{const [a,b,c,d,e,f,g]=await Promise.all([fetch(`${API}/api/admin/stats`,{headers}),fetch(`${API}/api/admin/queue`,{headers}),fetch(`${API}/api/admin/reports`,{headers}),fetch(`${API}/api/admin/analytics?days=14`,{headers}),fetch(`${API}/api/admin/users?limit=50`,{headers}),fetch(`${API}/api/admin/safety/events?limit=50`,{headers}),fetch(`${API}/api/admin/opportunities?limit=50`,{headers})]);if([a,b,c,d,e].some(x=>!x.ok))throw new Error("የአስተዳደር መግቢያ አልተሳካም።");setStats((await a.json()).data);setQueue((await b.json()).data);setReports((await c.json()).data);setAnalytics((await d.json()).data);setUsers((await e.json()).data);setSafetyEvents(f.ok?(await f.json()).data??[]:[]);const gx=await g.json();setOpps(g.ok&&gx?.data?(gx.data.items??[]):[]);localStorage.setItem("genzi_admin_key",key)}catch(e){setError(e instanceof Error?e.message:"ስህተት")}},[key,headers]);
 React.useEffect(()=>{void load()},[load]);
 async function post(path:string,body:unknown){const r=await fetch(`${API}${path}`,{method:"POST",headers:{...headers,"Content-Type":"application/json"},body:JSON.stringify(body)});const x=await r.json();if(!r.ok){setError(x.error??"ስህተት");return false}await load();return true}
 async function verifyModerator(){setError("");try{const r=await fetch(`${API}/api/admin/moderator-session`,{method:"POST",headers:{"X-Admin-Key":key,"Content-Type":"application/json"},body:JSON.stringify({code})});const x=await r.json();if(!r.ok||!x.data){setError(x.error??"ኮድ ትክክል አይደለም።");return}const label=x.data.moderator.firstName??x.data.moderator.username??x.data.moderator.id;setModeratorToken(x.data.token);setModeratorLabel(label);setCode("");localStorage.setItem("genzi_moderator_session",x.data.token);localStorage.setItem("genzi_moderator_label",label)}catch(e){setError(e instanceof Error?e.message:"ስህተት")}}
 function logoutModerator(){setModeratorToken("");setModeratorLabel("");localStorage.removeItem("genzi_moderator_session");localStorage.removeItem("genzi_moderator_label")}
 return <main><header><div className="brand"><img src="/genzi-icon-192.png" alt="GENZI" className="brand-logo"/><div><h1>🛡️ GENZI አስተዳደር</h1><small>🇪🇹 ኦፕሬሽን · ትንታኔ · ደህንነት</small></div></div><button onClick={()=>void load()}>↻ አድስ</button></header>
 <section className="auth panel"><input value={key} onChange={e=>setKey(e.target.value)} placeholder="Admin API Key" type="password"/><button onClick={()=>void load()}>ግባ</button></section>
 <section className="auth panel">{moderatorToken?<><span>✅ ገብተዋል እንደ {moderatorLabel}</span><button onClick={logoutModerator}>ውጣ</button></>:<><input value={code} onChange={e=>setCode(e.target.value)} placeholder="ከቦቱ /moderatorlogin የተላከ ኮድ"/><button onClick={()=>void verifyModerator()}>🔐 አረጋግጥ</button></>}</section>
 {!moderatorToken&&<p className="muted">ሪፖርቶችን ለመዝጋት ወይም ይዘት ለማጽደቅ/ውድቅ ለማድረግ በመጀመሪያ ለቦቱ /moderatorlogin ይላኩ እና የተላከውን ኮድ እዚህ ያረጋግጡ።</p>}
 {error&&<div className="error">⚠️ {error}</div>}
 <nav className="tabs"><button className={tab==="overview"?"active":""} onClick={()=>setTab("overview")}>📌 አጠቃላይ</button><button className={tab==="analytics"?"active":""} onClick={()=>setTab("analytics")}>📊 ትንታኔ</button><button className={tab==="safety"?"active":""} onClick={()=>setTab("safety")}>🛡️ ደህንነት</button><button className={tab==="users"?"active":""} onClick={()=>setTab("users")}>👥 ተጠቃሚዎች</button></nav>
 {tab==="overview"&&<><section className="grid">{[["👥 ተጠቃሚዎች",stats?.users??"—"],["📝 ፖስቶች",stats?.posts??"—"],["⚠️ ግምገማ",stats?.pending??"—"],["🛡️ ሞዴሬሽን",stats?.moderation??"—"]].map(([a,b])=><article key={a}><b>{a}</b><strong>{b}</strong></article>)}</section><section className="panel"><h2>🚨 የሚጠብቁ ይዘቶች</h2>{queue.length===0?<p className="muted">የሚጠብቅ ይዘት የለም።</p>:queue.map(x=><article className="queue" key={x.id}><div><b>{x.title??"ያልተሰየመ"}</b><p>{x.body??""}</p><small>👤 {x.user.firstName??x.user.username??x.user.telegramId} · {x.category??"—"}</small></div><div className="actions"><button onClick={()=>void post(`/api/admin/submissions/${x.id}/action`,{decision:"APPROVE"})}>✅ አጽድቅ</button><button onClick={()=>void post(`/api/admin/submissions/${x.id}/action`,{decision:"REJECT"})}>⛔ አትቀበል</button><button onClick={()=>void post(`/api/admin/submissions/${x.id}/action`,{decision:"RESTRICT"})}>🔒 ገድብ</button><button onClick={()=>void post(`/api/admin/submissions/${x.id}/action`,{decision:"BAN"})}>🚫 አግድ</button></div></article>)}</section><section className="panel"><h2>🚩 የተጠቃሚ ሪፖርቶች</h2>{reports.length===0?<p className="muted">ክፍት ሪፖርት የለም።</p>:reports.map(r=><article className="queue" key={r.id}><div><b>{r.post.title}</b><p>ምክንያት: {r.reason}<br/>{r.details??""}</p></div><div className="actions"><button onClick={()=>void post(`/api/admin/reports/${r.id}/resolve`,{action:"DISMISS"})}>✓ ዝጋ</button><button onClick={()=>void post(`/api/admin/reports/${r.id}/resolve`,{action:"REMOVE"})}>🗑️ አስወግድ</button></div></article>)}</section></>}
 {tab==="analytics"&&analytics&&<><section className="grid">{Object.entries(analytics.overview).map(([k,v])=><article key={k}><b>{labels[k]??k}</b><strong>{v.toLocaleString()}</strong></article>)}</section><section className="panel"><h2>📈 የ14 ቀን እንቅስቃሴ</h2><div className="series">{analytics.series.map(x=><div key={x.date} className="day"><small>{x.date.slice(5)}</small><span style={{height:`${Math.min(100,Math.max(6,x.views+x.posts*5+x.reactions*3))}%`}}></span><b>{x.views}</b></div>)}</div></section><section className="split"><section className="panel"><h2>📚 የይዘት ምድቦች</h2>{analytics.content.categories.map(x=><p className="row" key={x.category}><span>{x.category}</span><b>{x.count}</b></p>)}</section><section className="panel"><h2>🌟 ከፍተኛ ፈጣሪዎች</h2>{analytics.content.topCreators.map(x=><p className="row" key={x.id}><span>{x.firstName??x.username??x.id}</span><b>{x._count.posts} posts</b></p>)}</section></section></>}
 {tab==="safety"&&analytics&&<section className="split"><section className="panel"><h2>🛡️ የሞዴሬሽን እርምጃዎች</h2>{analytics.safety.moderationByAction.map(x=><p className="row" key={x.action}><span>{x.action}</span><b>{x.count}</b></p>)}</section><section className="panel"><h2>🚩 የሪፖርት ምክንያቶች</h2>{analytics.safety.reportsByReason.map(x=><p className="row" key={x.reason}><span>{x.reason}</span><b>{x.count}</b></p>)}</section></section>}
 {tab==="users"&&<section className="panel"><h2>👥 የቅርብ ተጠቃሚዎች</h2>{users.map(u=><article className="user" key={u.id}><div><b>{u.firstName??u.username??u.telegramId}</b><small>{u.role} · Level {u.level} · {u.xp} XP · {u._count.posts} posts · {u._count.followers} followers</small></div><div className="actions">{u.blocked?<button onClick={()=>void post(`/api/admin/safety/users/${u.id}/unban`,{})}>🔓 አንቃ</button>:<button onClick={()=>void post(`/api/admin/safety/users/${u.id}/restrict`,{hours:24})}>🔒 24ሰ ገድብ</button>}</div></article>)}</section>}
 </main>}
createRoot(document.getElementById("root")!).render(<App/>);
